
# Install helix (https://helix-editor.com).
tap "helix-editor/helix"
brew "helix", link: true

# Install flyctl (https://github.com/superfly/flyctl).
brew "superfly/tap/flyctl", link: true

# Install mosh.
brew "mosh", link: true

# Install ImageMagick.
brew "imagemagick@6" # v6
brew "imagemagick"   # v7

